cafet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from home import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('<int:table_num>/',views.home),
    path('register',views.signupView,name="signup"),
    path('login',views.signinView,name="signin"),
    path('cart',include('cart.urls')),
    path('main',views.main),
    path('order/', include('order.urls')),
    path('table/',include('Table.urls')),
 ]

cart/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='cart'

urlpatterns=[
	path('add/<int:product_id>/',views.add_cart,name='add_cart'),
	path('',views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
	path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
	path('history/' , views.orderHistory, name='order_history'),
	path('<int:order_id>/', views.viewOrder, name='order_detail'),
	
]

cart/models.py
from django.db import models
from home.models import Product

class Cart(models.Model):
	cart_id=models.CharField(max_length=250,blank=True)
	date_added=models.DateField(auto_now_add=True)

	class Meta:
		db_table='Cart'
		ordering=['date_added']

	def __self__(self):
		return self.cart_id

class CartItem(models.Model):
	product=models.ForeignKey(Product,on_delete=models.CASCADE)
	cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
	quantity=models.IntegerField()
	available=models.BooleanField(default=True)
	active=models.BooleanField(default=True)
	class Meta:
	 	db_table='CartItem'
	def sub_total(self):
	 	return self.product.price * self.quantity

	def __str__(self):
	 	return self.product

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from home.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import OrderItem,Order

def _cart_id(request):
	cart=request.session.session_key
	if not cart:
		cart=request.session.create()
	return cart

def add_cart(request,product_id):
	product=Product.objects.get(pid=product_id)
	try:
		cart=Cart.objects.get(cart_id=_cart_id(request))
	except Cart.DoesNotExist:
		cart=Cart.objects.create(cart_id=_cart_id(request))
		cart.save()

	try:
		cart_item=CartItem.objects.get(product=product,cart=cart)
		cart_item.quantity += 1
		cart_item.save()
	except CartItem.DoesNotExist:
		cart_item = CartItem.objects.create(product=product,quantity= 1 ,cart = cart)
		cart_item.save()
	return redirect('cart:cart_detail')



def cart_remove(request,product_id):
	cart=Cart.objects.get(cart_id=_cart_id(request))
	product=get_object_or_404(Product,pid=product_id)
	cart_item=CartItem.objects.get(product=product,cart=cart)
	if cart_item.quantity>1:
		cart_item.quantity-=1
		cart_item.save()
	else:
		cart_item.delete()
	return redirect('cart:cart_detail')


def full_remove(request,product_id):
	cart=Cart.objects.get(cart_id=_cart_id(request))
	product=get_object_or_404(Product,pid=product_id)
	cart_item=CartItem.objects.get(product=product,cart=cart)
	cart_item.delete()
	return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items = None):
	try:
		cart=Cart.objects.get(cart_id=_cart_id(request))
		cart_items=CartItem.objects.filter(cart=cart,active=True)

		for cart_item in cart_items: 
			total += (cart_item.product.price*cart_item.quantity)
			counter += cart_item.quantity

	except ObjectDoesNotExist:
		pass

	stripe.api_key = settings.STRIPE_SECRET_KEY
	stripe_total = int(total * 100)
	description = 'BRAND TABLE - NEW ORDER'
	data_key = settings.STRIPE_PUBLISHABLE_KEY
	if request.method == 'POST':
		#print(request.POST)
		try:
			token = request.POST['stripeToken']
			email = request.POST['stripeEmail']
			billingName = request.POST['stripeBillingName']
			billingAddress1 = request.POST['stripeBillingAddressLine1']
			billingCity = request.POST['stripeBillingAddressCity']
			billingPostcode = request.POST['stripeBillingAddressZip']
			billingCountry = request.POST['stripeBillingAddressCountryCode']
			shippingName = request.POST['stripeShippingName']
			shippingAddress1 = request.POST['stripeShippingAddressLine1']
			shippingCity = request.POST['stripeShippingAddressCity']
			shippingPostcode = request.POST['stripeShippingAddressZip']
			shippingCountry = request.POST['stripeShippingAddressCountryCode']
			customer = stripe.Customer.create(
					email=email,
					source=token
				)
			charge = stripe.Charge.create(
					amount=stripe_total,
					currency="inr",
					description=description,
					customer=customer.id
				)
			'''creating the order'''
			try:
				order_details = Order.objects.create(
					token = token,
					total = total,
					emailAddress = email,
					billingName = billingName,
					billingAddress1 = billingAddress1,
					billingCity = billingCity,
					billingPostcode = billingPostcode,
					billingCountry = billingCountry,
					shippingName = shippingName,
					shippingAddress1 = shippingAddress1,
					shippingCity = shippingCity,
					shippingPostcode = shippingPostcode,
					shippingCountry = shippingCountry,
					tableNo = request.session['table_num'],
					)
				order_details.save()
				for order_item in cart_items:
					oi = OrderItem.objects.create(
						product = order_item.product.name,
						quantity = order_item.quantity,
						price = order_item.product.price,
						order = order_details,
						tableNo = request.session['table_num']
						)
					oi.save()
					'''reduce stock when order is placed or saved'''
					products = Product.objects.get(id=order_item.product.id)
					products.save()
					order_item.delete()
					'''the terminal will print this message when order is saved'''
					print('the order has been created')
				return redirect('order:thanks', order_details.id)
			except ObjectDoesNotExist:
				pass
		except stripe.error.CardError as e:
			return False,e
	return render(request,'cart/cart.html',dict(cart_items=cart_items,total=total,counter=counter, data_key = data_key, stripe_total = stripe_total, description = description))



def orderHistory(request):
	if request.user.is_authenticated:
		email = str(request.user.email)
		print(email)
		order_details = Order.objects.filter(emailAddress=email)
	return render(request,'order/orders_list.html', {'order_details':order_details})


def viewOrder(request, order_id):
	if request.user.is_authenticated:
		email = str(request.user.email)
		order = Order.objects.get(id=order_id, emailAddress=email)
		order_items = OrderItem.objects.filter(order=order)
	return render(request, 'order/order_detail.html', {'order':order, 'order_items':order_items})

cart/templates/cart/cart.html
{% include 'base.html' %}
<!DOCTYPE html>
<html>
<head>
	<title>Green Chilli website</title>
	<meta charset="utf-8"/>
	<link rel="shortcut icon" type="../../../static/image/x-icon" href="../../../static/image/favicon.ico" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>

{% if not cart_items %}
	<div>
		<div class="text-center">
			<br>
			<h1 class="text-center my_title">
				Your shopping cart is Empty.
			</h1>
			<br>
			<p class="text-center">
				Please click<a href=main>here</a> to continue Shopping.
			</p>
		</div>
	</div>
{% else %}
	<div>
		<div class="text-center">
			<br>
			<h1 class="text-center my_title" style="margin-top: 5%;">
				Your Shopping Cart
			</h1>
			<br>
		</div>
		<div class="row mx-auto">
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
				<table class="table my_custom_table">
					<thead class="my_custom_thead">
						<tr>
							<th colspan="5">
								Your Items
							</th>
						</tr>
					</thead>
					<tbody>
						{% for cart_item in cart_items %}
							<tr>
								<td class="text-left">
									{{ cart_item.product.name }}
									<br>
									SKU. {{ cart_item.product.id }}
									<br>
									Unit Price. {{ car_item.product.price }}
									<br>
									Qty. {{ cart_item.quantity }}
								</td>
								<td>
									Rs. {{ cart_item.sub_total }}
								</td>
								{% if cart_item.available == True %}
									<td>
										<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a" > + </a>&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> - </a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id%}" class="custom_a">delete</a>
									</td>
								{% else %}
									<td>
										<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> - </a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id%}" class="custom_a">delete</a>
									</td>
								{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>

			</div>
{% endif %}
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
				<table class="table my_custom_table">
					<thead class="my_custom_thead">
						<tr>
							<th>Checkout</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								Please review your shopping cart items before proceeding the order.
							</td>
						</tr>
						<tr>
							<td class="text-left">
								Your total is : <strong> Rs. {{ total }}</strong>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="mx-auto">
					<form action="" method="POST">
						{% csrf_token %}
  						<script
    					src="https://checkout.stripe.com/checkout.js" class="stripe-button"
   						data-key="{{ data_key }}"
    					data-amount="{{ stripe_total }}"
    					data-name="Cafet"
    					data-description="{{ description }}"
    					data-currency="inr"
    					data-locale="auto"
  						data-shipping-address="true"
  						data-billing-address="true"
  						data-zip-code="true"
  						>
  						</script>
					</form>
					<a href="main" class="btn btn-success btn-block" style="margin-top: 5px;">Continue Shopping</a>
				</div>
				
			</div>
		</div>
	</div>
</body>
</html>