cafet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from home import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('<int:table_num>/',views.home),
    path('register',views.signupView,name="signup"),
    path('login',views.signinView,name="signin"),
    path('cart',include('cart.urls')),
    path('main',views.main),
    path('order/', include('order.urls')),
    path('table/',include('Table.urls')),
 ]

cart/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='cart'

urlpatterns=[
	path('add/<int:product_id>/',views.add_cart,name='add_cart'),
	path('',views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
	path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
	path('history/' , views.orderHistory, name='order_history'),
	path('<int:order_id>/', views.viewOrder, name='order_detail'),
	
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
	path('thanks/<int:order_id>/', views.thanks, name='thanks'),
	path('history/' , views.orderHistory, name='order_history'),
	path('<int:order_id>/', views.viewOrder, name='order_detail'),
]

order/models.py
from django.db import models


class Order(models.Model):
	tableNo = models.IntegerField(blank=False)
	id = models.AutoField(primary_key=True)
	token = models.CharField(max_length=250, blank=True)
	total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='INR Order Total')
	emailAddress = models.EmailField()
	created = models.DateTimeField(auto_now_add=True)
	billingName = models.CharField(max_length=250, blank=True)
	billingAddress1 = models.CharField(max_length=250, blank=True)
	billingCity = models.CharField(max_length=250, blank=True)
	billingPostcode = models.CharField(max_length=10, blank=True)
	billingCountry = models.CharField(max_length=200, blank=True)
	shippingName = models.CharField(max_length=250, blank=True)
	shippingAddress1 = models.CharField(max_length=250, blank=True)
	shippingCity = models.CharField(max_length=250, blank=True)
	shippingPostcode = models.CharField(max_length=10, blank=True)
	shippingCountry = models.CharField(max_length=200, blank=True)
	
	class Meta:
		db_table = 'Order'
		ordering = ['-created']

	def __str__(self):
		return str(self.id)

class OrderItem(models.Model):
	tableNo = models.IntegerField(blank=False)
	product = models.CharField(max_length=250)
	quantity = models.IntegerField()
	price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='INR Price')
	order = models.ForeignKey(Order, on_delete=models.CASCADE)

	class Meta:
		db_table = 'OrderItem'

	def sub_total(self):
		return self.quantity * self.price

	def __str__(self):
		return self.product		

order/views.py
from django.shortcuts import render, get_object_or_404
from .models import Order, OrderItem
from cart.models import Product
from django.contrib.auth.decorators import login_required

def thanks(request, order_id):
	if order_id:
		customer_order = get_object_or_404(Order, id=order_id)
	return render(request, 'thanks.html', {'customer_order': customer_order})

@login_required()
def orderHistory(request):
	if request.user.is_authenticated:
		email = str(request.user.email)
		print(email) 
		order_details = Order.objects.filter(emailAddress=email)
	return render(request,'order/orders_list.html', {'order_details':order_details})

def viewOrder(request, order_id):
	if request.user.is_authenticated:
		email = str(request.user.email)
		order = Order.objects.get(id=order_id, emailAddress=email)
		order_items = OrderItem.objects.filter(order=order)
	return render(request, 'order/order_detail.html', {'order':order, 'order_items':order_items})

order/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
<meta charset="utf-8"/>
<link rel="shortcut icon" type="../../static/image/x-icon" href="../../static/image/favicon.ico" />
<link rel="stylesheet"  href="..\..\static\bootstrap\css\base.css">
<link rel="stylesheet" href="..\..\static\bootstrap\css\bootstrap.min.css">
<link rel="stylesheet" href="..\..\static\bootstrap\css\bootstrap1.min.css">
</head>
<body>
	<div class="container k">
		<div container-fluid bg-light navbar-fixed-top my_top_navbar_div">
		{% include 'top-navbar.html' %}
		</div>
	</div>
</body>
</html>

order/templates/thanks.html
<!DOCTYPE html>
<html>
<head>
	<title>Green Chilli Restaurent</title>
	<meta charset="utf-8"/>
  <link rel="shortcut icon" type="../../../static/image/x-icon" href="../../../static/image/favicon.ico" /> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
<body>
</head>
<body>
	<div style="margin-top: 15%;">
		<div class="text-center" style="text-align:center; ">
			<br>
			<br>
			<h1 class="text-center my_title" style="text-align:center;">
				Thanks for placing your order
			</h1>
			<br>
			<br>
    
			<p>Your order number is:<b>{{ customer_order.id }}</b></p>
			<br>
			<p>
				We have received your order and will begin processing right away. For your records an email confirmation has been sent to you.
				It contains details of the items you purchased.
			</p>
		</div>
	</div>
	<br>
	<br>
  <a href="../../../main" class="btn btn-success btn-block" style="margin-top: 5px;">Continue Shopping</a>
</body>
<footer style="color:white;background-color: black;bottom:fixed;margin-top:250px;height: 2%; ">
  <p class="text-center"  ;">Contact us | This is me.</p>
</footer>
</html>
	

order/templates/top-navbar.html
<div class="container">
	<div class="l">
		<ul>
			
			<li>
				Welcome,<a href="{% url 'order:order_history' %}" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user.first_name}}<i class="fas fa-user-circle"></i></a>
				<div class="dropdown-menu dropdown-menu-right">
					<a href="{% url 'order:order_history' %}" class="dropdown-item"> Order History</a>
				</div>
			</li>
			<li>
				<a href="">Sign out <i class="fas fa-sign-out-alt"></i></a>
			</li>
			
			
		</ul>
	</div>
</div>